name: CI

on:
  push:
  pull_request:
  schedule:
    #At the end of every day
    - cron: 0 0 * * *

jobs:
  get-cmdstan-version:
    # get the latest cmdstan version to use as part of the cache key
    name: grab version
    runs-on: ubuntu-latest
    steps:
      - name: Get CmdStan version
        id: check-cmdstan
        run: |
            if [[ "${{ github.event.inputs.cmdstan-version }}" != "" ]]; then
              echo "::set-output name=version::${{ github.event.inputs.cmdstan-version }}"
            else
                echo "::set-output name=version::$(python -c 'import requests;print(requests.get("https://api.github.com/repos/stan-dev/cmdstan/releases/latest").json()["tag_name"][1:])')"
            fi
    outputs:
      version: ${{ steps.check-cmdstan.outputs.version }}

  build:
    needs: get-cmdstan-version

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint with flake8
      run: |

        python3 -m pip install --upgrade pip wheel;
        pip3 install flake8
        flake8 whimstan


    - name: Install dependencies
      run: |

        if [ "$RUNNER_OS" == "macOS" ]; then

        brew install c-blosc
        brew install hdf5

        fi


        pip3 install git+https://github.com/stan-dev/cmdstanpy.git flake8 numba numpy ipython scipy h5py matplotlib coverage pytest pytest-cov cython codecov arviz astropy tempita cryptography pyOpenSSL pyvo pyRXP;



        git clone https://github.com/threeML/astromodels.git
        cd astromodels
        git checkout dev
        python3 setup.py install
        cd ..


        git clone https://github.com/threeML/threeML.git
        cd threeML
        git checkout jmb_testing
        python3 setup.py install
        cd ..


    - name: Show libraries
      run: python -m pip freeze


    - name: CmdStan installation cacheing
      uses: actions/cache@v2
      with:
        path: ~/.cmdstan
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-cmdstan-${{ needs.get-cmdstan-version.outputs.version }}-${{ hashFiles('**/install_cmdstan.py') }}



    - name: Install CmdStan (Linux, macOS)
      run: |
        install_cmdstan -h
        install_cxx_toolchain -h
        python -m cmdstanpy.install_cmdstan --version ${{ needs.get-cmdstan-version.outputs.version }}


    - name: Install whimstan
      run: |
        python setup.py install

    - name: Test with pytest
      run: |
        python -m pytest -vv --cov=whimstan/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        files: ./coverage1.xml,./coverage2.xml
        directory: ./coverage/reports/

  # package:
  #   name: Build & verify package
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9

  #     - name: Install twine
  #       run: python -m pip install twine
  #     - name: Build package
  #       run: python setup.py sdist
  #     - name: List result
  #       run: ls -l dist
  #     - name: Check long_description
  #       run: python -m twine check dist/*




  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   name: Publish package
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install twine
  #     run: python -m pip install twine
  #   - name: Build package
  #     run: python setup.py sdist
  #   - uses: pypa/gh-action-pypi-publish@master
  #     with:
  #       user: __token__
  #       password: ${{ secrets.POPSYNTH_GITHUB_PYPI }}
